update java quickstarts for rooms
Azure-Samples/communication-services-java-quickstarts pull request #31
Opened 2022-07-22 17:57 UTC by shirleyqin-msft

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-07-28 20:30 UTC, shirleyqin-msft commented on rooms-quickstart-java/README.md
> +    `mvn install:install-file -Dfile=.\azure-communication-rooms\azure-communication-rooms-1.0.0-alpha.1.jar -DgroupId=com.azure -DartifactId=azure-communication-rooms -Dversion=1.0.0-alpha.1`
Will update this once the sdk is public

2022-07-28 20:30 UTC, shirleyqin-msft commented on rooms-quickstart-java/pom.xml
> +        <url>file://${project.basedir}\azure-communication-rooms</url>
will update this once the sdk is public

2022-07-29 17:37 UTC, moirf requested changes

2022-07-29 17:38 UTC, shirleyqin-msft commented on rooms-quickstart-java/src/main/java/com/communication/rooms/quickstart/App.java
> +    public static CommunicationRoom createRoom( RoomsClient roomsClient)
yeah that sounds better

2022-07-29 20:04 UTC, moirf approved these changes

2022-08-10 06:13 UTC, merged